### ISSUE TITLE
Fallback to object

### ISSUE THREAD

**Issue by mewwts** [flesler/hashmap#11]
Hi, is there a way to turn the HashMap-instance into a regular object (if the keys are valid, of course)?

**Comment by flesler** [comment]
Are your keys strings? they probably aren't, could do something like this:
```js
var obj = { };
hashmap.forEach(function(value, key) {
  obj[hashmap.hash(key)] = value;
});
```

**Comment by mewwts** [comment]
My keys would be strings, yes. Alright, I could probably live with that!

**Comment by flesler** [comment]
I don't understand. You want to use HashMap but at some point export an object? I thought that was the case. I'm not saying use string keys from start, else there's no point in using this module
