### ISSUE TITLE
Module boilerplate doesn't work as expected in webpack

### ISSUE THREAD

**Issue by fresheneesz** [flesler/hashmap#12]
The boilerplate at the top:

```
if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define([], factory);
} else ...
```

is triggered for webpack for some reason. This would work in the same way, except that you're not defining the AMD module in the same way as the commonJS module. The commonJS module is an object with a HashMap key set to the HashMap object, while the AMD one is directly set to the HashMap object. 

Could you make these more consistent by setting module.exports to factory() rather than exports.HashMap?

**Comment by flesler** [comment]
You mean like this?
```js
if (typeof define === 'function' && define.amd) {
  // AMD. Register as an anonymous module.
  define([], factory);
} else if (typeof module === 'object') {
  // Node js environment
  var HashMap = module.exports = factory();
  // Keep it backwards compatible
  HashMap.HashMap = HashMap;
} else {
  // Browser globals (this is window)
  this.HashMap = factory();
}
```

**Comment by fresheneesz** [comment]
Yeah, exactly

**Comment by fresheneesz** [comment]
Thanks! I had an issue in a project which would have caused me a lot of headache if this change wasn't made : )
