### ISSUE TITLE
Feature Request: forEach break

### ISSUE THREAD

**Issue by fresheneesz** [flesler/hashmap#18]
It would be nice for there to be some way to break from a `forEach`, say by returning `false` or `HashMap.break` or something. I suppose you can already do a `continue` just by returning undefined (or anything currently).

**Comment by flesler** [comment]
Hi, it's a nice feature I would sometimes need too. The thing is, this method imitates Array's forEach method, which should but lacks the ability to break. So I'm hesitant to implement something above the standard it's based on.

For now given how flexible JS is, I'd advise you to implement this outside the base code, either extend forEach or add some other method (like each()), if the feature request gets some traction I'll make the change.
