### ISSUE TITLE
Examples of search function 

### ISSUE THREAD

**Issue by allaboutapis** [flesler/hashmap#25]
I have been facing issues with hashmap when used with protractor for search function. Can you please post examples of search function of hashMap?

**Comment by flesler** [comment]
The examples I added are geared towards understanding the difference between this module and using a regular object as map, not to showcase methods.

`HashMap.search()` is like `Array.indexOf()` but for a key+value pair, here's an example:

```js
var HashMap = require('hashmap');
var map = new HashMap();
map.set(123, 'abc');
map.set(321, 'cba');
console.log(map.search('abc')); // 123 
```

You can play with this [here](https://tonicdev.com/576b2f8363c7a213009f67b7/576b2f848f03831300211e8c).
