### ISSUE TITLE
Wrong behaviour?

### ISSUE THREAD

**Issue by devlato** [flesler/hashmap#40]
Hello,

I've gone through your Readme and noticed the following issue:

> Objects as keys
> var key = {};
> var key2 = {};
> map.set(key, 123);
> map.set(key2, 321);
> map.get(key); // --> 123
> A regular Object used as a map would yield 321

Shouldn't `map.get(key)` return `321`? Because `hash(key)` should be equal to `hash(key2)` here as far as both objects has the same set of properties (basically, both have no own properties and the only difference is different placement in memory). But in your example it behaves like it just compares references.

**Comment by flesler** [comment]
Nope, each object is a different key. Is not based on the properties. I see how the other behavior might be useful sometimes too, but this is the one this library uses

**Comment by devlato** [comment]
@flesler Shouldn't there be a way to customize this behaviour then? I.e. Java implementation relays on `hashcode()` and `isEqual` method results.

**Comment by flesler** [comment]
@devlato it is based on the native [JavaScript Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set) before it was standarized. I can see how what you want could be needed, but it's feature that is not present. Also, it requires adding non-standard methods to objects (prototypes probably).

**Comment by bvandenbon** [comment]
> @flesler Shouldn't there be a way to customize this behaviour then? I.e. Java implementation relays on `hashcode()` and `isEqual` method results.

Exactly, and just for clarity.
In java, the hashcode is just used to put the keys in buckets (i.e. for faster retrieval).
But the java spec does not dictate that this hascode has to be unique. i.e. when multiple keys have the same hashcode, then still everything works fine. The keys get stored within the same bucket. But a bucket can by definition contain multiple keys with that same hashcode.

So, when an item is being retrieved using its key, then the hashcode is calculated of that key. Next it iterates the matches (i.e. the content of the matching bucket), and for each key in that bucket it uses the equals method.

So, in summary, making a hashcode more unique is a performance enhancement, but should have no impact on the actual behavior.

There are a couple of contracts regarding how a hashcode should be calculated. i.e. it should return the same value each time it is being called. That means that you should watch out how you calculate the hashcode for mutable objects. Or in other words: mutable objects make dangerous keys. But this is the nature of a hashmap. And secondly, if 2 objects are equal, they should also return the same hashcode.

There is also such a thing as an IdentityHashMap, which works exactly the same, but does not use the `equals` method to do the final mapping. Instead, it just uses the `==` operator.

---
But again, that's just how it works in java. And I have the impression that this is pretty much in line with how your implementation works. (Perhaps a little bit more like an IdentityHashMap I guess).

**Comment by flesler** [comment]
@bvandenbon this is not a port of Java's HashMap to JS, it's rather, as mentioned above, a class for maps whose keys can be almost anything. Supporting `hashcoode()` and `isEqual()` is not something I have in mind. Specially since JS now has native structures that fulfill the same roles. Thanks for you comment
