### ISSUE TITLE
The numbering inside "_data" object does not reset

### ISSUE THREAD

**Issue by PPrasai** [flesler/hashmap#41]
This might not be an issue, but possibly might cause problems in the long run.
I have a node+express REST API server which uses this HashMap library. I have noticed that the `_hmuid_` variable is not resetting. For every new request my server receives, the response has an incremented `_hmuid_`. Its no problem right now, but will it affect performance in the long run? following snippet shows first few lines of the hashmap:
```
{
    "_data": {
        "♦3": [
            "5b814a2322236100142ac9f6",
            [
                {
                    ...,
                    ...,
                    ...
                }
```

the `♦3` is not resetting back to `♦1`, so I think it is probably using some of my memory. Or is there something I'm doing wrong?

**Comment by flesler** [comment]
The idea is that objects are unique, if it resets then you don't ensure that.
I would personally don't be concerned about that being a performance issue. The only issue is the keys will get incrementally larger but not in a meaningfully negative way.

If you are still concerned, you can reset the counter by yourself by doing `HashMap.uid = 0` at your own risk :)
