### ISSUE TITLE
intigrating it into angualr application

### ISSUE THREAD

**Issue by rakeshpathuri** [flesler/hashmap#42]
hi i am trying to addthis library into my angualr applciation but thorwing error 

import { HashMap } from 'hashmap';

Could not find a declaration file for module 'hashmap'. 'c:/Users/z49445/Desktop/CrrCrewTkcUi/node_modules/hashmap/hashmap.js' implicitly has an 'any' type.
  Try `npm install @types/hashmap` if it exists or add a new declaration (.d.ts) file containing `declare module 'hashmap';`

is there a way to solve this  
thank you in advance

**Comment by flesler** [comment]
Hi, the module is not written in TS and the typings aren't available AFAIK. If you are willing to do them, I'll gladly incorporate it
