### ISSUE TITLE
Better hashing of keys

### ISSUE THREAD

**Issue by nicoladefranceschi** [flesler/hashmap#43]
I believe a better hashing is needed. Try this out:
```
var HashMap = require('hashmap')

var a = new HashMap();

a.set(['a', 'b', 'c'], 1)
a.set(['a', 'b', 'c'], 2)
a.set(['a', 'b⁞♠c'], 3)

console.log(a)
```
I'm able to generate two values with a collision for the keys when using array.

**Comment by flesler** [comment]
So, the first and the second, it's the expected behavior that they yield the same key. 

As for the third in comparison to the others, you basically went through the source code and checked how to generate a collision. Is this based on an issue found in production use?
