### ISSUE TITLE
Could you elaborate on the runtimes of the operations, basically get, set, multi and has?

### ISSUE THREAD

**Issue by incorelabs** [flesler/hashmap#45]
Hi, I'm curious to know the run-time of each of the operations, `get`, `set`, `multi` and `has`.

I wouldn't mind knowing the runtimes of the other functions. But mainly these.

**Comment by flesler** [comment]
Hi, not sure what you mean by run-time, whether it's complexity or, something else. You can check the code for that.

**Comment by incorelabs** [comment]
I mean, the Big O time complexity. :)

**Comment by flesler** [comment]
Correct, that's not available anywhere. Feel free to check the code for that. I'm closing this, questions are better done in public forums. Have a good one

**Comment by incorelabs** [comment]
I am aware of what the runtime should be. But since you have implemented the library and since it concerns data structures, the runtime is the only reason one would use the library. Shouldn't the information be published along with the readme itself.
