### ISSUE TITLE
Question: object as keys

### ISSUE THREAD

**Issue by alator21** [flesler/hashmap#46]
[bad English]
I have a project where i use class types for my objects.
e.g.
There is a UserId class wrapper that saves the id as a string 
UserId{value:string}

The thing is that i create this userid multiple times. e.g when i retrieve the value from the db i create a new object with the string value i get from the db.Essentially i create a new UserId object.

Based on how this library works,i cant i set my UserId class as a key to a hashmap because  the hash is reset every time i create a new instance.

the result i'm trying to achieve is 
let users:HashMap<UserId,User> = new HashMap<>();
users.set(new UserId("123"),user1);

let userId:UserId = new UserId("123");

let userIdSame:UserId = new UserId("123");

users.get(userId); //expect to be user1
users.get(userIdSame); //expect to be user1

Are there any plans to support such case? Thanks

EDIT:
Followup question: Shouldn't the hashing of an object depend only on the values of the instance? For example in Java two different instances with the same values, would have the same hashcode

**Comment by flesler** [comment]
Hi @alator21, I'm not currently devoting a lot of time to maintaining this. If you submit a PR I'd check it out. I don't think supporting this, is something that would justify a lot of underlying changes. To me, it's a somewhat uncommon use case (wrapping a primitive in an object but expecting it to be indexed like the primitive). You can solve it doing something like `id.getId()` before calling HashMap.

Also, JavaScript now has a native `Map` class. I think you'll see the same issue you have here, but might be worth investigating.

**Comment by alator21** [comment]
Hey @flesler , I am well aware of the native Map class, and the reason that i consider this library , is because of the said flaws. I might take a shot at implementing(and creating a PR) this at my spare time. Thanks for your time.

**Comment by AndrewDavis** [comment]
> Shouldn't the hashing of an object depend only on the values of the instance?

What you're probably looking for is to use a regular JS object, which will convert all keys over to strings before storing them, and then to override your keys' `toString()` functions. This way, you can have the key represent itself as whatever kind of string you want, i.e. based upon these or those values of the instance. There's an example of overriding `toString()` here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

**Comment by flesler** [comment]
Thanks for the response @AndrewDavis I'm closing this since it's not actionable
